# Building a love mad libs
first_name = input("Enter first name: ")
first_verb = input("Enter verb: ")
subject_in_school = input("Enter subject in school: ")
first_body_part = input("Enter a body part: ")
sound = input("Enter a sound: ")
color = input("Enter a color: ")
second_body_part = input("Enter a body part: ")
first_adjective = input("Enter an adjective: ")
second_verb = input("Enter a verb: ")
emotion = input("Enter an emotion: ")
first_noun = input("Enter a noun: ")
second_adjective = input("Enter an adjective: ")
second_noun = input("Enter a noun: ")

print("Dear " + first_name + " , ")
print("The first time i saw you my heart " + first_verb + " with joy.")
print("We were in " + subject_in_school + " class and you raised your " + first_body_part + " to ask a question.")
print("Your voice sounded like " + sound + " . ")
print("Then i noticed your " + color + second_body_part + " . ")
print("It is so " + first_adjective + " ! ")
print("Overall, I " + second_verb + " you. ")
print("I would tell you who i am but i'm too " + emotion + " . ")
print("Just know that the " + first_noun + " you received on Valentine's day is from me. ")
print("I hope you think its " + second_adjective + " . ")
print("Love, ")
print("Your " + second_noun + " Admirer ")
